import test from 'node:test';import assert from 'node:assert/strict';
import {KEY,fresh,load,save,normalize,resetRound,complete,spendHint,nextLevel,activateDay,earnedRank,activeDates} from '../dist/js/state.js';
const memory=()=>{const data=new Map();return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};};
test('Recargar mantiene marcas, vidas, ayudas agotadas y uso de ayuda',()=>{const s=fresh(),storage=memory();s.helps=0;s.round={marks:{2:'c',5:'x'},lives:1,usedHelp:true,helpStep:2,solved:false};save(storage,s);assert.deepEqual(load(storage).state,s);});
test('Tres reinicios restauran vidas en el mismo nivel sin borrar progreso ni uso de ayudas',()=>{const s=fresh();s.index=42;s.completed=42;s.round.usedHelp=true;for(const expected of [2,1,3]){resetRound(s);assert.equal(s.round.lives,expected);assert.equal(s.index,42);assert.equal(s.completed,42);assert.ok(s.round.usedHelp);}});
test('Completar, recargar y pulsar de nuevo no duplica recompensa',()=>{const s=fresh(),storage=memory();s.index=14;s.completed=14;s.streak=14;s.helps=2;assert.ok(complete(s));assert.equal(s.helps,3);save(storage,s);const again=load(storage).state;assert.equal(complete(again),false);assert.equal(resetRound(again),false);assert.equal(again.streak,0);assert.equal(again.completed,15);});
test('Una ayuda reinicia racha, tiene coste y tope de tres',()=>{const s=fresh();s.streak=14;for(let i=0;i<3;i++)assert.ok(spendHint(s));assert.equal(s.helps,0);assert.equal(s.streak,0);assert.equal(spendHint(s),false);});
test('Ayuda tutorial gratuita conserva ayudas pero rompe racha',()=>{const s=fresh();s.streak=9;assert.ok(spendHint(s,true));assert.equal(s.helps,3);assert.equal(s.streak,0);assert.ok(s.round.usedHelp);});
test('Cada 15 niveles sin ayuda da solo una ayuda hasta el tope',()=>{const s=fresh();s.helps=1;for(let i=0;i<30;i++){complete(s);nextLevel(s);}assert.equal(s.helps,3);assert.equal(s.streak,0);});
test('Práctica aislada no afecta a la partida',()=>{const main=fresh();main.index=54;main.completed=54;const before=JSON.stringify(main),practice=fresh();resetRound(practice);spendHint(practice,true);complete(practice);assert.equal(JSON.stringify(main),before);});
test('Final 100 y los diez rangos están cerrados correctamente',()=>{const s=fresh();s.index=99;s.completed=99;complete(s);assert.equal(nextLevel(s),false);assert.equal(s.completed,100);assert.equal(earnedRank(9),'Primeros pasos');assert.equal(earnedRank(10),'Explorador');assert.equal(earnedRank(90),'Gran estratega');assert.equal(earnedRank(100),'Mente Claret');});
test('Racha diaria: repetición, siete días, salto de día y mejor marca',()=>{const s=fresh();s.helps=1;for(let day=1;day<=7;day++){const date=new Date(2026,8,day,12);assert.ok(activateDay(s,date).changed);assert.equal(activateDay(s,date).changed,false);}assert.equal(s.helps,2);assert.equal(s.daily.current,7);assert.equal(s.daily.best,7);activateDay(s,new Date(2026,8,9,12));assert.equal(s.daily.current,1);assert.equal(s.daily.best,7);assert.deepEqual([...activeDates(s.daily)],['2026-09-09']);});
test('Cambio de mes y año cuenta como día consecutivo',()=>{const s=fresh();activateDay(s,new Date(2026,11,31,12));activateDay(s,new Date(2027,0,1,12));assert.equal(s.daily.current,2);});
test('Reloj atrasado no permite repetir recompensa',()=>{const s=fresh();activateDay(s,new Date(2026,8,9,12));assert.equal(activateDay(s,new Date(2026,8,8,12)).changed,false);});
test('Guardado corrupto o bloqueado no impide iniciar',()=>{const storage=memory();storage.setItem(KEY,'{broken');assert.ok(load(storage).warning);assert.equal(load(storage).state.index,0);assert.equal(save({setItem(){throw Error('blocked')}},fresh()),false);});
test('Migración V2 conserva cero ayudas y nivel',()=>{const storage=memory();storage.setItem('claretLevel25','25');storage.setItem('claretHelps25','0');const {state}=load(storage);assert.equal(state.helps,0);assert.equal(state.index,22);assert.equal(state.completed,22);assert.equal(state.tutorialDone,true);});
test('Datos fuera de rango se normalizan',()=>{const s=normalize({index:900,helps:-9,streak:900,round:{marks:{99:'c',1:'bad',3:'x'},lives:-3}});assert.equal(s.index,0);assert.equal(s.helps,3);assert.equal(s.round.lives,3);assert.deepEqual(s.round.marks,{3:'x'});});

test('Dos prácticas terminan sin sumar retos, rangos ni rachas',async()=>{const {beginTutorial,advanceTutorial}=await import('../dist/js/state.js');const s=fresh(),p=beginTutorial(s);p.round.solved=true;assert.ok(advanceTutorial(s,p,true));assert.equal(p.index,1);assert.equal(s.completed,0);p.round.solved=true;assert.equal(advanceTutorial(s,p,true),false);assert.ok(s.tutorialDone);assert.equal(s.completed,0);assert.equal(s.streak,0);assert.equal(s.helps,3);});
test('La introducción se recupera tras recargar sin tocar la campaña',async()=>{const {beginTutorial}=await import('../dist/js/state.js');const s=fresh();s.tutorialIndex=1;s.tutorialRound.marks={2:'c'};const storage=memory();save(storage,s);const restored=load(storage).state,p=beginTutorial(restored);assert.equal(p.index,1);assert.equal(p.round.marks[2],'c');assert.equal(restored.completed,0);});
test('Migración RC1 conserva la partida al descontar las dos prácticas',async()=>{const {migrateV3}=await import('../dist/js/state.js');const s=fresh();s.version=3;s.index=15;s.completed=15;s.round.marks={4:'c'};const migrated=migrateV3(s);assert.equal(migrated.index,13);assert.equal(migrated.completed,13);assert.deepEqual(migrated.round.marks,{4:'c'});assert.ok(migrated.tutorialDone);});
test('Repetir prácticas ya realizadas no modifica el progreso',async()=>{const {beginTutorial,advanceTutorial}=await import('../dist/js/state.js');const s=fresh();s.tutorialDone=true;s.completed=60;s.index=60;const before=JSON.stringify(s),p=beginTutorial(s,true);p.round.solved=true;advanceTutorial(s,p,false);p.round.solved=true;advanceTutorial(s,p,false);assert.equal(JSON.stringify(s),before);});

test('Los destinos presentados se conservan y se normalizan sin duplicados',()=>{const s=normalize({seenWorlds:[0,0,4,9,-1,10,'2']});assert.deepEqual(s.seenWorlds,[0,4,9]);const freshState=fresh();assert.deepEqual(freshState.seenWorlds,[]);});
